### ISSUE TITLE
Support for snapshot versions

### ISSUE THREAD

**Issue by StizzurpXDD** [mc-wiki/minecraft-mod-heywiki#18]
### Describe the feature

There are many major snapshots like 24w14potato which should have this mod ported to because of the amount of time spent on the page. Not just 24w14potato, but also for upcoming latest snapshots.

### Reason for the feature

Support for snapshot versions would also help players to know about something in the snapshot (for eg.24w14poatato).

### How important is this feature to you?

8

### Additional information and screenshots

This support should be implemented for not just future snapshots, but also for previous major snapshots like 23w13a_or_b.

**Comment by Dianliang233** [comment]
Snapshots will be supported in the future. Old snapshot will never be supported.
