### ISSUE TITLE
Hey Wiki conflicts with EMI

### ISSUE THREAD

**Issue by keatit71** [mc-wiki/minecraft-mod-heywiki#23]
### Steps to reproduce

Install EMI and Hey Wiki and try to run it.

### Describe the bug

When trying to use EMI and Hey Wiki together they crash the game because of Hey Wiki doing something with the recipe screen mixins.

### Expected behavior

The Game should open without crashing

### Mod version

1.3.1

### Game version

1.20.4

### Operating system

Windows 11 22635.3500

### Mod loader

Fabric

### Mod loader version

0.15.10

### Relevant log/crash report output

Crash Log:
[crash-2024-04-20_16.27.46-client.txt](https://github.com/mc-wiki/minecraft-mod-heywiki/files/15047471/crash-2024-04-20_16.27.46-client.txt)

### How frustrating is this bug?

10

**Comment by Dianliang233** [comment]
Thanks!

**Comment by Dianliang233** [comment]
https://github.com/mc-wiki/minecraft-mod-heywiki/releases/tag/v1.3.2%2B1.20.4
