### ISSUE TITLE
v1.4.0 bug

### ISSUE THREAD

**Issue by NyteWL** [mc-wiki/minecraft-mod-heywiki#27]
### Steps to reproduce

1. Install Hey Wiki v1.4.0 and dependencies.
2. Launch the game.
3. Enter a world.
4. Point the crosshair at any block/entity.

### Describe the bug

The confirmation screen pops up automatically, even if I don't press H.

### Mod version

1.4.0

### Game version

1.20.4

### Operating system

Windows 10

### Mod loader

Fabric

### Mod loader version

0.15.10

**Comment by Dianliang233** [comment]
fixed in 1.4.1+1.20.4
