### ISSUE TITLE
Compatibility Issue with Iris Shaders

### ISSUE THREAD

**Issue by NyteWL** [mc-wiki/minecraft-mod-heywiki#31]
### Steps to reproduce

1. Install Fabric Loader and API
2. Install Hey Wiki and its dependencies, Iris Shaders, and Sodium
3. Start the game
4. Put a shader pack with lang files in shaderpacks folder and load it
5. Open the shader pack settings screen and check for the error

### Describe the bug

Hey Wiki seems to cause Iris to be unable to read the shader pack's lang file:
![image0](https://github.com/mc-wiki/minecraft-mod-heywiki/assets/163705449/3850d950-769d-44fe-aa3d-75adf4d59ee0)
chinese screen:
![image2](https://github.com/mc-wiki/minecraft-mod-heywiki/assets/163705449/4bfd5303-9ccc-4e76-9a41-a8385fa58f64)

### Expected behavior

Normally, the shader pack settings screen should look like this:
![image](https://github.com/mc-wiki/minecraft-mod-heywiki/assets/163705449/ecee042b-84d4-4f73-a4c4-314bffa7ba44)
chinese:
![image1](https://github.com/mc-wiki/minecraft-mod-heywiki/assets/163705449/425bda57-82c7-4169-949f-043eb4b10e16)

### Mod version

1.4.1

### Game version

1.20.4

### Operating system

Windows 10

### Mod loader

Fabric

### Mod loader version

0.15.11

### Relevant log/crash report output

https://mclo.gs/v4svZFt

**Comment by Dianliang233** [comment]
Relates to this mixin to TranslationStorage (yarn):
https://github.com/IrisShaders/Iris/blob/1.20.6/src/main/java/net/irisshaders/iris/mixin/MixinClientLanguage.java
