### ISSUE TITLE
Mekanism wiki

### ISSUE THREAD

**Issue by ae1313** [mc-wiki/minecraft-mod-heywiki#43]
### Mod name

Mekanism

### Wiki URL

https://wiki.aidancbrady.com/wiki/

### Official status

- [X] This wiki is an official wiki for the mod.
- [ ] This wiki is not an official wiki for the mod and is community-run.

### Is the wiki a fork?

- [ ] This wiki is a fork of another wiki and it has more information.
- [X] This wiki is has never been forked.

### Comprehensiveness

- [ ] This wiki is comprehensive and has a page for every item, block, entity, etc.
- [ ] This wiki is not comprehensive and is missing pages.
- [X] This wiki is not very comprehensive yet, but it is being actively worked on to include a page for every item, block, entity, etc.

### Does the mod support the mod loader and Minecraft version Hey Wiki supports?

- [X] Yes, the mod is compatible with Hey Wiki.
- [ ] No, the mod is not compatible with Hey Wiki.

### Additional information and screenshots

It is the process of being updated, but gets a lot of the mod

### Confirmation

- [X] I have searched for this wiki on Hey Wiki and it is not already supported.
- [X] I have completed the above form to the best of my ability.

**Comment by Dianliang233** [comment]
Out in v1.5.2
