### ISSUE TITLE
Adding Language Variant Option

### ISSUE THREAD

**Issue by tszhangchan** [mc-wiki/minecraft-mod-heywiki#44]
### Describe the feature

In the Chinese Minecraft Wiki, there are 3 language variants offered, including
- Simplified Chinese (China mainland) 大陆简体
- Traditional Chinese (Hong Kong) 香港繁體
- Traditional Chinese (Taiwan) 台灣繁體
- not to convert 不转换
<img width="463" alt="3 language variants and not to convert option in Chinese Minecraft Wiki" src="https://github.com/mc-wiki/minecraft-mod-heywiki/assets/59113254/12edeaa7-b2dd-40d3-95b3-2b16db9c14b8">

---

The language variants can affect the content. For example,

Article 'Creeper' in Traditional Chinese (Hong Kong):
<img width="1011" alt="Article 'Creeper' in Traditional Chinese (Hong Kong)" src="https://github.com/mc-wiki/minecraft-mod-heywiki/assets/59113254/5258890b-b0ba-40d8-9ee9-4bda2eb39c96">

Article 'Creeper' when not to convert is chosen:
<img width="1074" alt="Article 'Creeper' when not to convert is chosen" src="https://github.com/mc-wiki/minecraft-mod-heywiki/assets/59113254/b1774670-4f5d-4079-a7ba-1218ae55abcf">
Licensed under [CC BY-NC-SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/)

---

I suggest adding an option for language variants in the mod settings, including the 3 language variants and the default one.

Language variants can be changed by adding a query `variant`.
For example, `?variant=zh-cn` stands for the Simplified Chinese (China mainland) variant.
`zh-hk`: Traditional Chinese (Hong Kong) 
`zh-tw`: Traditional Chinese (Taiwan)
Omitting the query or using `zh` represents not converting.

### Reason for the feature

The option can offer a more fluent and enjoyable experience to those who prefer other language variants over the default one.

### How important is this feature to you?

8

### Additional information and screenshots

The expected effect:
![The expected effect](https://github.com/mc-wiki/minecraft-mod-heywiki/assets/59113254/d6bf4dab-428c-4542-a103-5e22e6977995)

**Comment by Dianliang233** [comment]
Great feature request. Can't believe I missed this.

**Comment by Dianliang233** [comment]
Out in v1.5.2
