### ISSUE TITLE
Game crashes when I click the keybind

### ISSUE THREAD

**Issue by EitiFrie** [mc-wiki/minecraft-mod-heywiki#48]
### Steps to reproduce

1. Open the game
2. Enter a world
3. Click the keybind for opening the wiki page for the block/entity/item you're looking at
4. Wait approximately 5 seconds

### Describe the bug

The game crashes shortly after I click my keybind to open wiki page for the block/entity/item I'm looking at

### Mod version

1.5.1

### Game version

1.20.4

### Operating system

Windows 10

### Mod loader

Fabric

### Mod loader version

0.15.11

### Relevant log/crash report output

[crash-2024-06-17_20.49.03-client.txt](https://github.com/user-attachments/files/15875075/crash-2024-06-17_20.49.03-client.txt)

https://mclo.gs/RMWgxnB

### How frustrating is this bug?

7.8/10

### Additional information and screenshots

This only happens when I click the keybind to open a wiki page.
When I use a command to open a wiki page there are no issues at all.

I use a lot of mods so maybe that's related to my issue. You can check the log linked in this bug report to see what mods I'm using.

**Comment by Dianliang233** [comment]
This is kinda weird. The stacktrace seems to be pointing out that OptiGUI is the issue, but I can't reproduce it with OptiGUI on. I'll later try some more combinations. It would be helpful if you could send me a zip file of your mod directory?

**Comment by EitiFrie** [comment]
> It would be helpful if you could send me a zip file of your mod directory?

https://drive.google.com/file/d/1IOxw03BkHA52tyXmzL9O7LTqiFt0e7eS/view

**Comment by Dianliang233** [comment]
Hi, I checked your mod file and can confirm that the issue is indeed caused by optigui. I wasn't able to reproduce it because I was using [a newer version of the mod](https://modrinth.com/mod/optigui/version/2.3.0-beta.2) which seems to have it fixed. Could you try to use this version and see if the issue persists? Or if you don't have any resource packs that depend on it, you can just disable it IG.

**Comment by EitiFrie** [comment]
Ok thank you

**Comment by EitiFrie** [comment]
> Could you try to use this version and see if the issue persists?

Yes thank you, that fixed it.
