### ISSUE TITLE
Applied energistics wiki

### ISSUE THREAD

**Issue by ae1313** [mc-wiki/minecraft-mod-heywiki#49]
### Mod name

Applied Energistics(AE2)

### Wiki URL

https://guide.appliedenergistics.org/

### Official status

- [X] This wiki is an official wiki for the mod.
- [ ] This wiki is not an official wiki for the mod and is community-run.

### Is the wiki a fork?

- [ ] This wiki is a fork of another wiki and it has more information.
- [X] This wiki is has never been forked.

### Comprehensiveness

- [X] This wiki is comprehensive and has a page for every item, block, entity, etc.
- [ ] This wiki is not comprehensive and is missing pages.
- [ ] This wiki is not very comprehensive yet, but it is being actively worked on to include a page for every item, block, entity, etc.

### Does the mod support the mod loader and Minecraft version Hey Wiki supports?

- [X] Yes, the mod is compatible with Hey Wiki.
- [ ] No, the mod is not compatible with Hey Wiki.

### Additional information and screenshots

The items blocks and machines section has the blocks. There is a different sub guide for each version, like https://guide.appliedenergistics.org/1.2X.X

### Confirmation

- [X] I have searched for this wiki on Hey Wiki and it is not already supported.
- [X] I have completed the above form to the best of my ability.

**Comment by Dianliang233** [comment]
Because this isn't a MediaWiki site and requires some special URL formatting, I will need a bit more time to work on this
