### ISSUE TITLE
Performance issues - Freezes for seconds when typing any command.

### ISSUE THREAD

**Issue by TngySt** [mc-wiki/minecraft-mod-heywiki#55]
### Steps to reproduce

1. When in-game, open the chat.
2. Type a slash to tell the game you are about to enter a command.
3. The game freezes for several seconds each time you type a character.

### Describe the bug

It seems to be a performance issue when typing something as a command. There is no issue when typing a chat message. Also, the Wiki pages suggestions are always suggested as a command prediction, even when I haven't typed "/wiki" yet, as soon as I type a "/", the lag occurs, even when typing a basic command such as "/gamemode" or "/ThatCouldBeAnything".

### Expected behavior

I would have expected to not freeze when trying to type a command.

### Mod version

1.5.2

### Game version

1.21

### Operating system

Windows 10

### Mod loader

Fabric

### Mod loader version

0.15.11

### How frustrating is this bug?

9

**Comment by Dianliang233** [comment]
Unfortunately I can't reproduce this issue. Do you have other mods installed? Could you provide a log from your `.minecraft/logs` directory?
