### ISSUE TITLE
Chat colors are removed while using Hey Wiki

### ISSUE THREAD

**Issue by cadenkriese** [mc-wiki/minecraft-mod-heywiki#57]
### Steps to reproduce

1. Install Hey Wiki
2. Visit a multiplayer server that uses colors in the chat
3. Notice the lack of colors in the chat.

### Describe the bug

Messages that normally contain color in the chat appear white while using Hey Wiki.

### Expected behavior

The chat colors should remain consistent with vanilla.

### Mod version

1.5.2+1.21

### Game version

1.21

### Operating system

Windows 11

### Mod loader

Fabric

### Mod loader version

0.15.11

### How frustrating is this bug?

8

**Comment by Dianliang233** [comment]
Please check if 1.5.3 fixes this

**Comment by cadenkriese** [comment]
Yup, my case is fixed in 1.5.3. Thank you for your effort!
