### ISSUE TITLE
Game simply crashes with mod enabled

### ISSUE THREAD

**Issue by hablethedev** [mc-wiki/minecraft-mod-heywiki#58]
### Steps to reproduce

1. Download Fabulously Optimized 1.21 6-alpha2
2. Install Hey Wiki & dependency
3. Run game (MultiMC)
Game crashes!

### Describe the bug

Game crashes on launch.

### Expected behavior

Game shows menu and runs normally.

### Mod version

1.5.3

### Game version

1.21

### Operating system

Ubuntu 22.04

### Mod loader

Fabric

### Mod loader version

0.15.11

### Relevant log/crash report output

Log: https://pastebin.com/sExLhZVi password: `heywiki`
Crash log: https://files.catbox.moe/bnozsp.txt  no pass

### How frustrating is this bug?

9.9 recurring

### Additional information and screenshots

I'm on a very bad Laptop: Intel Celeron N1420, 4GB RAM, Integrated UHD Graphics

**Comment by Dianliang233** [comment]
I think this is a compatibility issue with Remove Reloading Screen

**Comment by Dianliang233** [comment]
seems like to trigger this you need three mods installed at once: rrls, zoomify, and hey wiki

**Comment by hablethedev** [comment]
Well that's weird. Taking out Zoomify fixes the issue or should I also remove RRLS?

**Comment by Dianliang233** [comment]
You only need to take out one of the three and it should work. I still have no idea why this is happening

**Comment by ssterling** [comment]
Reproduced on my end, too; it only happens with all three.

**Comment by ArduFish123** [comment]
Can confirm

**Comment by ArduFish123** [comment]
Also reporting this to Remove Reloading Screen and the other mods would be a good idea.

**Comment by Dianliang233** [comment]
Fixed in v1.6.0
