### ISSUE TITLE
API for adding new wikis

### ISSUE THREAD

**Issue by newtykip** [mc-wiki/minecraft-mod-heywiki#59]
### Describe the feature

Allow mods to integrate with the mod and embed wikis associated with themselves.

### Reason for the feature

It prevents people needing to update the mod to get new wikis they want, and providing wikis that are irrelevant for a player.

**Comment by Dianliang233** [comment]
Hi, please see if https://github.com/mc-wiki/minecraft-mod-heywiki#resource-pack fulfills your use case
