### ISSUE TITLE
Add 1.20.6 LTS instead of 1.20.4?

### ISSUE THREAD

**Issue by LoweredgamesDev** [mc-wiki/minecraft-mod-heywiki#60]
### Describe the feature

I think it makes more sense since it's the latest version of 1.20.X

### How important is this feature to you?

1

**Comment by MetalManeMc** [comment]
I _think_ this is because most mods that use version 1.20.4 haven't updated to 1.20.6, so more players use .4 than .6.
Though this might be false due to my limited knowledge of Java Minecraft.

**Comment by Dianliang233** [comment]
1.20.6 is more like 1.21, that's why. I know it's not a very reasonable explanation but I don't really want to cherry pick twice every time I update something :)

**Comment by Loweredgames** [comment]
ok
