### ISSUE TITLE
Steam Overlay Integration

### ISSUE THREAD

**Issue by MoiraPrime** [mc-wiki/minecraft-mod-heywiki#61]
### Describe the feature

I'm not sure if it's possible for non-steam games to hook into the steam API, but if it is, it would be useful if heywiki links could open in the steam overlay instead of your default browser.

### Reason for the feature

If this is possible to implement, it would be useful to not have to alt-tab to see the wiki page for whatever item you're looking into.

### How important is this feature to you?

7

**Comment by Dianliang233** [comment]
According to https://partner.steamgames.com/doc/features/overlay, Steam Overlay only supports games launched by Steam.

**Comment by Dianliang233** [comment]
Also this issue is being tracked at #10
