### ISSUE TITLE
Suggestion for Stardust Labs Wiki

### ISSUE THREAD

**Issue by ultim-0** [mc-wiki/minecraft-mod-heywiki#62]
### Mod name

Terralith, Structory, Incendium, and Nullscape

### Wiki URL

https://stardustlabs.miraheze.org/

### Language

English

### Official status

- [X] This wiki is an official wiki for the mod.
- [ ] This wiki is not an official wiki for the mod and is community-run.

### Is the wiki a fork?

- [ ] This wiki is a fork of another wiki and it has more information.
- [X] This wiki is has never been forked.

### Comprehensiveness

- [X] This wiki is comprehensive and has a page for every item, block, entity, etc.
- [ ] This wiki is not comprehensive and is missing pages.
- [ ] This wiki is not very comprehensive yet, but it is being actively worked on to include a page for every item, block, entity, etc.

### Does the mod support the mod loader and Minecraft version Hey Wiki supports?

- [X] Yes, the mod is compatible with Hey Wiki.
- [ ] No, the mod is not compatible with Hey Wiki.

### Confirmation

- [X] I have searched for this wiki on Hey Wiki and it is not already supported.
- [X] I have completed the above form to the best of my ability.

**Comment by Dianliang233** [comment]
I don't think it's practical to support datapacks for now

**Comment by ultim-0** [comment]
Although these mods are usually constructed with datapacks, they can be loaded with mod loaders. See links below for more info:
* https://www.curseforge.com/minecraft/mc-mods/terralith
* https://www.curseforge.com/minecraft/mc-mods/structory
* https://www.curseforge.com/minecraft/mc-mods/incendium
* https://www.curseforge.com/minecraft/mc-mods/nullscape

**Comment by Dianliang233** [comment]
These jars are not real mods. They are datapacks in disguise. The real problem with datapacks is the fact that they cannot add new item. This makes it hard for the mod to properly resolve a page for the "item". The fact whether it's packaged as a mod or not doesn't matter.

**Comment by ultim-0** [comment]
The "Items" in datapacks does not matter, because these packs mainly modify the world generation by introducing new biomes like `terralith:snowy_badlands`, `incendium:inverted_forest`, and `nullscape:shadowlands`. Therefore, what I expect to see is: when typing `/whatbiome` in these biomes, the game opens the corresponding pages (for example, https://stardustlabs.miraheze.org/wiki/Snowy_badlands ) instead of searching something like `biome.terralith.snowy_badlands` in Minecraft Wiki, returning nothing.
