### ISSUE TITLE
Use data components to link custom items

### ISSUE THREAD

**Issue by TheGallium** [mc-wiki/minecraft-mod-heywiki#64]
### Describe the feature

Allow servers that add custom items to put data components (NBT before 1.20.5) with links for the item's wiki page.
For exemple: `[custom_data={heywiki_link:"exemple.com"}]`

### Reason for the feature

Servers and mapmakers could easily add compatibility with HeyWiki.
Big servers like the Hypixel Skyblock, and smaller ones would benefit from this.

### How important is this feature to you?

8, im a server maker that has a wiki

**Comment by Dianliang233** [comment]
This is a very interesting suggestion. However, having something like `heywiki_link` is not going to work well with hey wiki's current wiki resolving system. Perhaps we can have something like this:

1. You need to use [the current system](https://github.com/mc-wiki/minecraft-mod-heywiki#resource-pack) to register a new wiki with a custom namespace using resource pack. If it is not feasible to ask your players to download a resource pack, we can also embed it into the mod itself.
2. We will have `heywiki:identifier` and `heywiki:translation_key` in custom_data

However this only accounts for custom items.

**Comment by Dianliang233** [comment]
This has been implemented in 1.5.5. Please open a new issue if the current approach does not fit your use case.
