### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by cat67315** [mc-wiki/minecraft-mod-heywiki#68]
### Steps to reproduce

open the game

### Describe the bug

it crashes

### Expected behavior

it should not crash

### Mod version

v1.5.6+1.21 with fabric

### Game version

1.21

### Operating system

Windows 11

### Mod loader

Fabric

### Mod loader version

0.16.0

### Relevant log/crash report output

[latest.log](https://github.com/user-attachments/files/16503577/latest.log)

### How frustrating is this bug?

10

**Comment by cat67315** [comment]
I removed the Remove Reloading Screen mod and it didn't crash anymore so I guess it's fixed but I would like compatibility with it in the future.

**Comment by Dianliang233** [comment]
Duplicate of #58
